application:
  name: cart_management
  token:
    expiration:
      login: 2592000 # 30 days
      otp: 5 # 5 minutes

  encryption:
    jwt:
      algorithm: RS256
      private_key: /etc/tex-corver/jwt/private_key.pem
      public_key: /etc/tex-corver/jwt/public_key.pem
      expiration: 2592000 # 30 days

  google_oauth:
    client_id: 294428498927-aj221bh0l2ab6vh3lp1209l3qpar97hu.apps.googleusercontent.com
    project_id: auth-429101
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_secret: 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
    redirect_uris:
      - http://localhost:32000/oauth/google_oauth2/callback
      - https://hoaem.vn/oauth/google_oauth2/callback

  otp:
    require:
      login: false
      register: false
      reset_password: true

    expiration:
      login: 5 # 5 minutes
      register: 5 # 5 minutes
      reset_password: 5 # 5 minutes